### ISSUE TITLE
在macOS下无法安装插件，开发者给的回复和解决办法

### ISSUE THREAD

**Issue by edok10** [J-11/Aseprite-Simplified-Chinese#2]
> Hi there,
>
>Thanks for reporting this bug. Actually it looks like a problem with the file inside the .zip named "!使用方法!.txt". If you remove the "!" it should work.
Anyway we'll fix this crash for the next release.
>
>As a side note about your extension, I recommend you to change the "name" property in your "package.json", you can try to use something like "name": "schinese-extension" instead of the generic name "language-extension".
>
>Best regards,
>David

**Comment by J-11** [comment]
感谢反馈，已经在新版本更新中做出更改。
