### ISSUE TITLE
aseprite v1.3-rc4-dev 无法汉化

### ISSUE THREAD

**Issue by RainHoutas** [J-11/Aseprite-Simplified-Chinese#6]
![屏幕截图 2023-07-13 090322](https://github.com/J-11/Aseprite-Simplified-Chinese/assets/97776439/a002db3c-33b8-4593-a9a7-17f14bb74126)

如图，是版本问题吗？

**Comment by J-11** [comment]
很抱歉现在才看到，目前Aseprite已经更新到rc6版本，不知道您更新后还能否正常安装汉化。
如果依然出错，可以尝试手动安装：
Edit > Preferences > Extensions > Add Extensions 选择汉化文件进行安装。
