### ISSUE TITLE
你好，需要更新汉化版本，我们以将后续版本汉化补足

### ISSUE THREAD

**Issue by 66six11** [J-11/Aseprite-Simplified-Chinese#7]
需要更新版本，我们想将汉化好的文件并入您的社区，并将其并入到aseprite的官方社区，方便更多热爱像素，使用aseprite的用户。因为这里不支持.aseprite-extension格式，所这里的文件为.zip格式
这里是我们的联系qq：2652915018
[hanhua-1.3.1.zip](https://github.com/J-11/Aseprite-Simplified-Chinese/files/13497809/hanhua-1.3.1.zip)

**Comment by 66six11** [comment]
抱歉打扰到您，如果您比较忙，我们希望可以得到你的汉化包的授权，因为该汉化是在您rc1版本之上进行后续的汉化。

**Comment by Cetaceaqua** [comment]
你可以尝试先 fork 这个仓库，提交你的更改后再发起 Pull request，在 pr 被通过后更改就被更新到仓库中了

**Comment by 66six11** [comment]
> 你可以尝试先 fork 这个仓库，提交你的更改后再发起 Pull request，在 pr 被通过后更改就被更新到仓库中了

谢谢你的建议，我再尝试一下这个方式，上次我想通过这样的方式，但平台要求2fa验证，没弄成功
